version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - mvn clean package
      - pipenv run aws s3 cp target/bookit-aws-lambda-1.0-SNAPSHOT.jar s3://bookit-aws-lambda-bucket/build-bookit-aws-lambda/bookit-aws-lambda-1.0-SNAPSHOT.jar
      - pipenv run sam deploy --template-file fargateTaskScaler.yaml --force-upload --capabilities CAPABILITY_NAMED_IAM --region eu-north-1 --stack-name serverlessrepo-fargateTaskScaler