version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
       - mvn clean package
artifacts:
  files:
    - target/bookit-aws-lambda-1.0-SNAPSHOT.jar
  discard-paths: yes