version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
       - mvn clean package
  post_build:
    commands:
artifacts:
  secondary-artifacts:
    artifact1: 
      files:
         - 'target/bookit-aws-lambda-1.0-SNAPSHOT.jar'
      discard-paths: yes
    