AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A lambda function for scaling fargate tasks defined by the input parameters. This function is invoked by scheduled CloudWatch rules.
Resources:
  fargateTaskScaler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: se.knowit.bookit.aws.taskscaling.FargateTaskScaler::handleRequest
      Runtime: java11
      CodeUri: target/bookit-aws-lambda-1.0-SNAPSHOT.jar
      AutoPublishAlias: live
      Description: ''
      MemorySize: 320
      Timeout: 15
      Role: arn:aws:iam::194896174337:role/service-role/EcsTaskScheduleLambdaFunction-role-4765ou0z
      DeploymentPreference:
        Type: AllAtOnce
